version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO # Keep console less verbose
    formatter: simple
    stream: ext://sys.stdout

  # This file handler appends all logs (level DEBUG and above from root)
  # to model.log. The 'simple' formatter includes the datetime.
  file:
    class: logging.FileHandler
    level: DEBUG # Log everything to the file
    formatter: simple
    filename: model.log
    mode: 'a' # Append mode
    encoding: utf8

root:
  level: DEBUG
  handlers: [console, file]
