name: Build and Push Inference Image to ACR (No Deploy)

on:
  push:
    branches:
      - main
    paths:
      - 'Inference/**'

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MODELWRAPPERSAVING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MODELWRAPPERSAVING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MODELWRAPPERSAVING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push inference image to ACR (no deploy)
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Inference
          registryUrl: questregistry.azurecr.io
          registryUsername: ${{ secrets.MODELWRAPPERSAVING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MODELWRAPPERSAVING_REGISTRY_PASSWORD }}
          resourceGroup: quest-ai
          imageToBuild: questregistry.azurecr.io/model-wrapper-inference:${{ github.sha }}
