name: Deploy Saving Service to Azure Container Apps

on:
  push:
    branches:
      - main
    paths:
      - 'saving/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MODELWRAPPERSAVING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MODELWRAPPERSAVING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MODELWRAPPERSAVING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image to ACR, then deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/saving
          registryUrl: questregistry.azurecr.io
          registryUsername: ${{ secrets.MODELWRAPPERSAVING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MODELWRAPPERSAVING_REGISTRY_PASSWORD }}
          containerAppName: model-wrapper-saving
          resourceGroup: quest-ai
          imageToBuild: questregistry.azurecr.io/model-wrapper-saving:${{ github.sha }}
