name: Build and Push Inference Image to ACR

on:
  push:
    branches:
      - main
    paths:
      - 'Inference/**'

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MODELWRAPPERSAVING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MODELWRAPPERSAVING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MODELWRAPPERSAVING_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR using username/password
        run: echo "${{ secrets.MODELWRAPPERSAVING_REGISTRY_PASSWORD }}" | docker login questregistry.azurecr.io -u ${{ secrets.MODELWRAPPERSAVING_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image from Inference/
        run: docker build -t questregistry.azurecr.io/model-wrapper-inference:${{ github.sha }} ./Inference

      - name: Push Docker image to ACR
        run: docker push questregistry.azurecr.io/model-wrapper-inference:${{ github.sha }}
